"use client";

import { useEffect, useMemo, useState } from "react";
import { denmarkNet, germanyNet, italyNet, portugalNet, spainNet, switzerlandNet } from "./tax";

type Country = "nl" | "pt" | "de" | "ch" | "es" | "dk" | "it" | "gb";
type City = "Amsterdam" | "Rotterdam" | "Lisbon" | "Porto" | "Berlin" | "Munich" | "Zurich" | "Geneva" | "Madrid" | "Barcelona" | "Copenhagen" | "Aarhus" | "Milan" | "Rome" | "London" | "Manchester";
type Info = { name:string; code:string; currency:string; symbol:string; salary:number; min:number; max:number; step:number; regime?:string; regimeShort?:string; regimeHint?:string };

const countryInfo:Record<Country,Info> = {
  nl:{name:"Netherlands",code:"NL",currency:"EUR",symbol:"€",salary:72000,min:20000,max:180000,step:1000,regime:"30% ruling",regimeShort:"30% ruling",regimeHint:"Up to 30% of qualifying pay may be tax-free."},
  pt:{name:"Portugal",code:"PT",currency:"EUR",symbol:"€",salary:60000,min:15000,max:160000,step:1000,regime:"IFICI (NHR 2.0)",regimeShort:"IFICI",regimeHint:"20% rate on eligible Portuguese-source employment income."},
  de:{name:"Germany",code:"DE",currency:"EUR",symbol:"€",salary:75000,min:20000,max:200000,step:1000},
  ch:{name:"Switzerland",code:"CH",currency:"CHF",symbol:"CHF",salary:110000,min:40000,max:300000,step:2000},
  es:{name:"Spain",code:"ES",currency:"EUR",symbol:"€",salary:60000,min:15000,max:180000,step:1000,regime:"Beckham Law",regimeShort:"Beckham Law",regimeHint:"24% employment-income rate up to €600,000 for eligible inbound workers."},
  dk:{name:"Denmark",code:"DK",currency:"DKK",symbol:"kr",salary:600000,min:200000,max:1800000,step:10000,regime:"Researcher / highly paid employee tax scheme",regimeShort:"Expat scheme",regimeHint:"32.84% combined gross tax for up to seven years; highly paid employees need DKK 65,400 per month in 2026, plus ATP."},
  it:{name:"Italy",code:"IT",currency:"EUR",symbol:"€",salary:65000,min:15000,max:180000,step:1000,regime:"Impatriate regime",regimeShort:"Impatriate",regimeHint:"Eligible workers may receive a 50% employment-income exemption, up to the €600,000 annual limit."},
  gb:{name:"United Kingdom",code:"UK",currency:"GBP",symbol:"£",salary:70000,min:18000,max:200000,step:1000},
};
const countryOrder:Country[]=["nl","pt","de","ch","es","dk","it","gb"];
const cities:Record<Country,City[]>={nl:["Amsterdam","Rotterdam"],pt:["Lisbon","Porto"],de:["Berlin","Munich"],ch:["Zurich","Geneva"],es:["Madrid","Barcelona"],dk:["Copenhagen","Aarhus"],it:["Milan","Rome"],gb:["London","Manchester"]};
const livingCosts:Record<City,{rent:number;groceries:number;utilities:number;transport:number;leisure:number;childcare:number}>={
  Amsterdam:{rent:2100,groceries:475,utilities:260,transport:125,leisure:350,childcare:1050},Rotterdam:{rent:1650,groceries:450,utilities:250,transport:110,leisure:310,childcare:950},Lisbon:{rent:1450,groceries:350,utilities:170,transport:50,leisure:260,childcare:480},Porto:{rent:1100,groceries:325,utilities:160,transport:40,leisure:230,childcare:420},Berlin:{rent:1450,groceries:390,utilities:250,transport:85,leisure:280,childcare:350},Munich:{rent:1950,groceries:430,utilities:270,transport:70,leisure:320,childcare:500},Zurich:{rent:2450,groceries:650,utilities:260,transport:95,leisure:450,childcare:1800},Geneva:{rent:2300,groceries:670,utilities:250,transport:75,leisure:430,childcare:1700},Madrid:{rent:1500,groceries:360,utilities:180,transport:55,leisure:280,childcare:550},Barcelona:{rent:1650,groceries:370,utilities:190,transport:50,leisure:300,childcare:600},Copenhagen:{rent:14500,groceries:3900,utilities:1650,transport:750,leisure:2800,childcare:3900},Aarhus:{rent:10000,groceries:3600,utilities:1550,transport:560,leisure:2400,childcare:3400},Milan:{rent:1650,groceries:390,utilities:220,transport:40,leisure:300,childcare:650},Rome:{rent:1450,groceries:380,utilities:220,transport:35,leisure:290,childcare:600},London:{rent:2300,groceries:430,utilities:260,transport:210,leisure:390,childcare:1400},Manchester:{rent:1300,groceries:360,utilities:230,transport:95,leisure:300,childcare:1050},
};

function progressiveTax(income:number,bands:[number,number][]) { let tax=0,previous=0; for(const [ceiling,rate] of bands){tax+=Math.max(0,Math.min(income,ceiling)-previous)*rate;previous=ceiling;if(income<=ceiling)break} return tax }
function dutchGeneralCredit(income:number){if(income<=29736)return 3115;if(income>=78426)return 0;return 3115-.06398*(income-29736)}
function dutchLabourCredit(income:number){if(income<=11965)return .08324*income;if(income<=25845)return 996+.31009*(income-11965);if(income<=45592)return 5300+.0195*(income-25845);if(income<=132920)return Math.max(0,5685-.0651*(income-45592));return 0}
function netherlandsNet(gross:number,ruling:boolean,includeSocial:boolean){const taxFree=ruling?Math.min(gross*.3,78600,Math.max(0,gross-48013)):0;const taxable=gross-taxFree;const payrollTax=progressiveTax(taxable,[[38883,.081],[78426,.3756],[Infinity,.495]]);const socialTax=includeSocial?Math.min(taxable,38883)*.2765:0;const generalCredit=dutchGeneralCredit(taxable);const labourCredit=dutchLabourCredit(taxable);const tax=Math.max(0,payrollTax+socialTax-generalCredit-labourCredit);return{net:gross-tax,tax,social:socialTax,taxable,taxFree,generalCredit,labourCredit,payrollTax,socialTax}}
function ukNet(gross:number){const allowance=Math.max(0,12570-Math.max(0,gross-100000)/2);const taxable=Math.max(0,gross-allowance);const tax=progressiveTax(taxable,[[37700,.2],[125140-allowance,.4],[Infinity,.45]]);const social=Math.max(0,Math.min(gross,50270)-12570)*.08+Math.max(0,gross-50270)*.02;return{net:gross-tax-social,tax,social,taxable,taxFree:allowance,generalCredit:0,labourCredit:0,payrollTax:tax,socialTax:social}}
function payrollFor(country:Country,gross:number,useRegime:boolean,city:City,includeSocial:boolean,researcher:boolean){if(country==="nl")return netherlandsNet(gross,useRegime,includeSocial);if(country==="pt")return portugalNet(gross,useRegime);if(country==="de")return germanyNet(gross);if(country==="es")return spainNet(gross,useRegime,city as "Madrid"|"Barcelona");if(country==="it")return italyNet(gross,useRegime,city as "Milan"|"Rome");if(country==="dk")return denmarkNet(gross,useRegime,researcher,city as "Copenhagen"|"Aarhus");if(country==="gb")return ukNet(gross);return switzerlandNet(gross,city as "Zurich"|"Geneva")}

function Globe(){return <div className="globe" aria-hidden="true"><svg viewBox="0 0 360 360" fill="none"><g stroke="currentColor"><circle cx="180" cy="180" r="174"/><ellipse cx="180" cy="180" rx="112" ry="174"/><ellipse cx="180" cy="180" rx="48" ry="174"/><ellipse cx="180" cy="180" rx="174" ry="112"/><ellipse cx="180" cy="180" rx="174" ry="48"/></g><path className="route routeA" d="M55 198 Q180 48 306 190"/><path className="route routeB" d="M42 236 Q190 330 322 208"/><circle className="node nodeA" cx="55" cy="198" r="4"/><circle className="node nodeB" cx="306" cy="190" r="4"/><circle className="node nodeC" cx="322" cy="208" r="4"/></svg></div>}

export default function Home(){
  const[country,setCountry]=useState<Country>("nl"),[city,setCity]=useState<City>("Amsterdam"),[salary,setSalary]=useState(72000),[kids,setKids]=useState(0),[regime,setRegime]=useState(true),[rentMode,setRentMode]=useState<"solo"|"share">("solo"),[holidayMode,setHolidayMode]=useState<"included"|"onTop">("included"),[holidayPayout,setHolidayPayout]=useState<"spread"|"may">("spread"),[includeSocial,setIncludeSocial]=useState(true),[researcher,setResearcher]=useState(false),[heroIndex,setHeroIndex]=useState(0);
  useEffect(()=>{const timer=window.setInterval(()=>setHeroIndex(i=>(i+1)%countryOrder.length),2800);return()=>window.clearInterval(timer)},[]);
  const gross=useMemo(()=>{const holidayAllowance=country==="nl"?(holidayMode==="included"?salary*(8/108):salary*.08):0;const baseSalary=country==="nl"&&holidayMode==="included"?salary-holidayAllowance:salary;return{annualGross:baseSalary+holidayAllowance,baseSalary,holidayAllowance}},[country,holidayMode,salary]);
  const result=useMemo(()=>{const payroll=payrollFor(country,gross.annualGross,regime,city,includeSocial,researcher);const base=livingCosts[city];const rent=rentMode==="share"?base.rent*.62:base.rent;const health=country==="nl"?165:country==="ch"?420:["pt","es","it"].includes(country)?55:0;const household=rent+base.groceries+base.utilities+base.transport+base.leisure+health+kids*base.childcare;const averageMonthlyNet=payroll.net/12;const holidayNet=gross.holidayAllowance?gross.holidayAllowance*(payroll.net/gross.annualGross):0;const monthlyNet=holidayPayout==="may"&&gross.holidayAllowance?(payroll.net-holidayNet)/12:averageMonthlyNet;return{...payroll,...gross,holidayNet,averageMonthlyNet,monthlyNet,household,savings:monthlyNet-household,rent,health}},[country,city,regime,includeSocial,researcher,rentMode,kids,holidayPayout,gross]);
  const comparison=useMemo(()=>{if(!countryInfo[country].regime)return null;const standard=payrollFor(country,gross.annualGross,false,city,includeSocial,researcher);const special=payrollFor(country,gross.annualGross,true,city,includeSocial,researcher);return{standard,special,gain:special.net-standard.net}},[country,city,gross.annualGross,includeSocial,researcher]);
  const formatter=useMemo(()=>new Intl.NumberFormat("en",{style:"currency",currency:countryInfo[country].currency,maximumFractionDigits:0}),[country]);const money=(n:number)=>formatter.format(n);const compact=(n:number)=>`${countryInfo[country].symbol}${new Intl.NumberFormat("en",{notation:"compact",maximumFractionDigits:0}).format(n)}`;
  const costs=livingCosts[city];const costRows:[string,number][]=[["Housing",result.rent],["Groceries",costs.groceries],["Utilities",costs.utilities],["Transport",costs.transport],["Health",result.health],["Lifestyle",costs.leisure],...(kids?[[`Childcare × ${kids}`,costs.childcare*kids] as [string,number]]:[])];const heroCountry=countryOrder[heroIndex],heroCity=cities[heroCountry][0];const deductionRate=result.annualGross?(result.annualGross-result.net)/result.annualGross*100:0,taxShare=result.annualGross?result.tax/result.annualGross*100:0,socialShare=country==="nl"?0:result.annualGross?result.social/result.annualGross*100:0;
  function chooseCountry(next:Country){setCountry(next);setCity(cities[next][0]);setSalary(countryInfo[next].salary);setRegime(Boolean(countryInfo[next].regime));setResearcher(false)}
  return <main>
    <nav className="nav"><a className="brand" href="#top"><span className="brandMark">T</span><span>Takehome Atlas</span><em>Global salary explorer</em></a><div className="navLinks"><a href="#calculator">Calculator</a><a href="#method">Methodology</a></div><span className="yearBadge"><i/>2026 tax rules</span></nav>
    <section className="hero" id="top"><div className="heroCopy"><div className="eyebrow"><span>●</span> NET SALARY, HONESTLY</div><h1>What would you actually keep in <span key={heroCity}>{heroCity}</span>?</h1><p>Compare take-home pay, expat tax regimes and city living costs before you accept the offer.</p><div className="heroStats"><div><b>8</b><small>Countries</small></div><div><b>5</b><small>Expat regimes</small></div><div><b>16</b><small>Cities</small></div></div></div><div className="heroVisual"><Globe/><div className="floatingCity"><span>{countryInfo[heroCountry].code}</span><div><small>Currently comparing</small><b>{heroCity}</b></div></div></div></section>
    <section className="calculator" id="calculator"><div className="sectionHead"><div><span className="step">01</span><div><span className="eyebrow">YOUR SCENARIO</span><h2>Run the numbers</h2></div></div><p>Indicative annual tax calculation for an employee under retirement age.</p></div><div className="workspace">
      <form className="inputs" onSubmit={e=>e.preventDefault()}><div className="inputHeading"><div><span className="eyebrow">WHERE IS THE JOB?</span><h3>Choose a country</h3></div><span>{countryInfo[country].code}</span></div><div className="countryToggle">{countryOrder.map(item=><button type="button" key={item} className={country===item?"active":""} onClick={()=>chooseCountry(item)}><span>{countryInfo[item].code}</span>{countryInfo[item].name}{countryInfo[item].regime&&<i title="Expat regime available"/>}</button>)}</div><p className="regimeLegend"><i/>Expat regime available</p>
        <div className="twoCol"><label><span className="fieldLabel">CITY</span><select value={city} onChange={e=>setCity(e.target.value as City)}>{cities[country].map(item=><option key={item}>{item}</option>)}</select></label><label><span className="fieldLabel">CHILDREN</span><select value={kids} onChange={e=>setKids(Number(e.target.value))}><option value="0">No children</option><option value="1">1 child</option><option value="2">2 children</option><option value="3">3 children</option></select></label></div>
        <label className="salaryField"><span className="fieldLabel">GROSS ANNUAL SALARY · {countryInfo[country].currency}</span><span className="salaryInput"><i>{countryInfo[country].symbol}</i><input aria-label="Gross annual salary" type="number" min={countryInfo[country].min} step={countryInfo[country].step} value={salary} onChange={e=>setSalary(Number(e.target.value))}/><em>/ year</em></span></label><input className="range" aria-label="Salary slider" type="range" min={countryInfo[country].min} max={countryInfo[country].max} step={countryInfo[country].step} value={salary} onChange={e=>setSalary(Number(e.target.value))}/><div className="rangeEnds"><span>{compact(countryInfo[country].min)}</span><span>{compact(countryInfo[country].max)}</span></div>
        {country==="nl"&&<div className="holidayCard"><Setting label="8% holiday allowance" hint="Is vakantiegeld part of the salary above?"><Segment options={[["included","Included"],["onTop","On top"]]} value={holidayMode} set={v=>setHolidayMode(v as "included"|"onTop")}/></Setting><Setting label="Payment timing"><Segment options={[["spread","Spread"],["may","Paid in May"]]} value={holidayPayout} set={v=>setHolidayPayout(v as "spread"|"may")}/></Setting></div>}
        {country==="nl"?<section className="taxSettings"><span className="fieldLabel">DUTCH TAX SETTINGS</span><Toggle label="30% ruling" hint="Up to 30% of qualifying pay may be tax-free." checked={regime} onChange={setRegime}/><Toggle label="National insurance" hint="AOW, Anw and Wlz contributions." checked={includeSocial} onChange={setIncludeSocial}/><InfoBox><b>Who may qualify?</b> Generally, employees recruited abroad with scarce expertise who meet the distance and salary tests. Your employer applies with you.</InfoBox></section>:countryInfo[country].regime?<><section className="taxSettings"><span className="fieldLabel">EXPAT TAX REGIME</span><Toggle label={countryInfo[country].regime!} hint={countryInfo[country].regimeHint!} checked={regime} onChange={setRegime}/></section>{country==="dk"&&regime&&<InfoBox standalone><b>{researcher?"Approved researcher route selected.":salary>=65400*12?"Highly paid salary test met.":"Highly paid salary test not met."}</b> The 2026 threshold is DKK 65,400 per month plus ATP.<label><input type="checkbox" checked={researcher} onChange={e=>setResearcher(e.target.checked)}/>I qualify as an approved researcher</label></InfoBox>}</>:<div className="standardCard"><span className="fieldLabel">TAX TREATMENT</span><b>Standard resident taxation</b><small>{country==="ch"?"The selected city drives the canton and municipality estimate.":"Single employee without optional personal deductions."}</small></div>}
        <div className="housingRow"><span><b>Housing</b><small>How will you live?</small></span><div><button type="button" className={rentMode==="solo"?"selected":""} onClick={()=>setRentMode("solo")}>My own place</button><button type="button" className={rentMode==="share"?"selected":""} onClick={()=>setRentMode("share")}>Shared</button></div></div>
      </form>
      <aside className="results" aria-live="polite"><div className="resultTop"><span>YOUR ESTIMATED OUTCOME</span><b>{city}, {countryInfo[country].code} · {countryInfo[country].currency}</b></div><section className="netBlock"><small>TAKE-HOME IN {countryInfo[country].name}</small><div className="netValue"><strong>{money(result.monthlyNet)}</strong><span>per month</span></div><p>{holidayPayout==="may"&&result.holidayAllowance?`Regular month · May adds about ${money(result.holidayNet)} net holiday pay`:"Annualized over 12 months"}</p><div className="summaryStats"><Stat label="Annual net" value={money(result.net)}/><Stat label="Total deductions" value={`${deductionRate.toFixed(1)}%`}/><Stat label="Gross package" value={money(result.annualGross)}/></div></section>
        <section className="breakdownCard"><CardTitle title="Where the money goes" sub="Annual gross split line by line." value={money(result.annualGross)}/><div className="breakdownBar"><i style={{width:`${Math.max(0,100-taxShare-socialShare)}%`}}/><i style={{width:`${taxShare}%`}}/><i style={{width:`${socialShare}%`}}/></div><div className="breakdownRows"><BreakdownRow color="gold" label="Net income" value={money(result.net)}/><BreakdownRow color="clay" label={country==="nl"?"Payroll tax & national insurance":"Income tax"} value={`− ${money(result.tax)}`}/>{country!=="nl"&&<BreakdownRow color="mint" label="Employee social contributions" value={`− ${money(result.social)}`}/>}<BreakdownRow label="Taxable income" value={money(result.taxable)}/></div></section>
        {comparison&&<section className="comparisonCard"><div className="cardTitle"><div><span className="eyebrow">REGIME COMPARISON</span><h3>{countryInfo[country].regimeShort}</h3></div><span>{money(comparison.gain/12)} more / month</span></div><div className="comparisonGrid"><div className={!regime?"active":""}><small>Standard taxation</small><b>{money(comparison.standard.net/12)}</b><span>per month</span></div><div className={regime?"active":""}><small>With {countryInfo[country].regimeShort}</small><b>{money(comparison.special.net/12)}</b><span>per month</span></div></div><p>Potential annual difference: <b>{money(comparison.gain)}</b>. Eligibility requirements still apply.</p></section>}
        <section className={`savings ${result.savings<0?"negative":""}`}><span><small>POSSIBLE SAVINGS</small><b>{money(result.savings)}</b><em>each month after estimated costs</em></span><strong>{Math.round(result.savings/result.monthlyNet*100)}% <small>of net</small></strong></section><section className="costBreakdown"><CardTitle title="Monthly cost estimate" sub={`${city} · ${rentMode==="solo"?"own place":"shared"}`} value={money(result.household)}/><div className="costMeter"><span style={{width:`${Math.min(100,Math.max(0,result.household/result.monthlyNet*100))}%`}}/></div><p className="costShare">Living costs use approximately {Math.round(result.household/result.monthlyNet*100)}% of net income</p>{costRows.map(([name,amount])=><div className="costRow" key={name}><span>{name}</span><b>{money(amount)}</b></div>)}</section><p className="resultNote">A planning estimate in local currency, not tax advice. Family, pension, benefit and personal-deduction rules may materially change the result.</p>
      </aside>
    </div></section>
    <section className="method" id="method"><div className="methodHead"><span className="step">02</span><div><span className="eyebrow">THE METHOD</span><h2>One offer. The whole picture.</h2></div></div><div className="methodGrid"><article><b>01</b><h3>Net pay</h3><p>Progressive income tax, employee contributions and applicable credits modeled annually.</p></article><article><b>02</b><h3>Local costs</h3><p>City-level housing, transport, utilities, food, health and childcare assumptions.</p></article><article><b>03</b><h3>Expat regimes</h3><p>Compare the indicative impact while keeping eligibility caveats visible.</p></article></div></section><footer><a className="brand" href="#top"><span className="brandMark">T</span><span>Takehome Atlas</span></a><p>See what you’ll take home, wherever you go.</p><span>2026 · PLANNING ESTIMATE</span></footer>
  </main>
}

function Toggle({label,hint,checked,onChange}:{label:string;hint:string;checked:boolean;onChange:(v:boolean)=>void}){return <button type="button" className="toggleRow" role="switch" aria-checked={checked} onClick={()=>onChange(!checked)}><span><b>{label}</b><small>{hint}</small></span><i className={`switch ${checked?"on":""}`}><em/></i></button>}
function InfoBox({children,standalone=false}:{children:React.ReactNode;standalone?:boolean}){return <div className={`eligibility ${standalone?"standalone":""}`}><span>i</span><p>{children}</p></div>}
function Setting({label,hint,children}:{label:string;hint?:string;children:React.ReactNode}){return <div className="settingLead"><span><b>{label}</b>{hint&&<small>{hint}</small>}</span>{children}</div>}
function Segment({options,value,set}:{options:string[][];value:string;set:(v:string)=>void}){return <div className="segmented">{options.map(([v,label])=><button type="button" key={v} className={value===v?"selected":""} onClick={()=>set(v)}>{label}</button>)}</div>}
function Stat({label,value}:{label:string;value:string}){return <div><small>{label}</small><b>{value}</b></div>}
function CardTitle({title,sub,value}:{title:string;sub:string;value:string}){return <div className="cardTitle"><div><h3>{title}</h3><p>{sub}</p></div><span>{value}</span></div>}
function BreakdownRow({label,value,color}:{label:string;value:string;color?:"gold"|"mint"|"clay"}){return <div><span>{color&&<i className={color}/>} {label}</span><b>{value}</b></div>}
